version: "3"

services:
  app:
    command: >
      sh -c "poetry run python drf/manage.py migrate && poetry run python drf/manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/drf/app
    ports:
      - "8000:8000"
    depends_on:
      drfdb:
        condition: service_healthy
    env_file:
      - .env

  drfdb:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: