# Generated by Django 5.2.5 on 2025-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_salebook_quantity_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salebook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
